#!/usr/bin/env python3
"""
q102_modular_hamiltonian_spectrum_v1.py — K_ω spectrum on Q102.

Per S181 (Cor_Q102_morphogenesis_time_canonical), the canonical algebraic
time on Q102 is the Tomita-Takesaki modular flow σ_t^ω = Ad(ρ_ω^{it})
generated by K_ω = -log ρ_ω.  At the spectral-action thermal vacuum
ω_β = e^{-βD²/Λ²}/Z, ρ_ω = e^{-βD²/Λ²}/Z, so K_ω = β·D²/Λ² + log Z.

The SPECTRUM of K_ω at this state is therefore (β/Λ²) · spec(D²) + const.
The ratios of K_ω eigenvalues are intrinsic — independent of β, Λ, and
the additive constant.  Computing spec(D²) on Q102's spectral triple is
elementary linear algebra on the 102×102 (or H ⊗ H' = 102² = 10404 dim)
operator.  This is observation-only per S180 — no time-stepping, no
state evolution.

Reports:
  - Full spectrum spec(D), spec(D²)
  - Eigenvalue gap structure (ground state + first excited)
  - Near-zero modes (vacuum manifold tangent space)
  - Number of distinct eigenvalues (degeneracy structure)
  - Comparison with the closure-quotient family member spectra (Q48, Q98)
    if same construction is run there

Aaron Green — May 5, 2026 — first follow-up to S181.
"""

import sys, time
import numpy as np
from collections import Counter

sys.path.insert(0, '.')
from quotient_landscape_autopoiesis_v1 import (
    haar_C3, complete_edges, adjacent_edges,
)
from q102_build_v1 import build_c_closed_quotient, build_J
from q102_orderone_v1 import (
    j_compatible_triplets, build_representation, incremental_order_one,
)
from g6a_multiscale_spectral_v1 import (
    G0_cyclic, adjacent_ternary, combined_adj_stride2, build_laplacian,
    build_sample_DF,
)


def compute_modular_spectrum(name, seed_fn, psi_init, depth=4):
    """Build Q, build D = L + α·D_F at natural scale, compute spec(D), spec(D²)."""
    print(f"\n{'═'*78}")
    print(f"  {name}")
    print(f"{'═'*78}")

    t0 = time.time()
    seed_edges = seed_fn()
    Q = build_c_closed_quotient(seed_edges, psi_init, depth=depth)
    n = Q['n_cl']
    print(f"  [build] Q: n={n}, hyperedges={len(Q['q_he'])}, "
          f"({time.time()-t0:.1f}s)")

    J, _ = build_J(Q)
    L, adj, deg = build_laplacian(Q)

    D_F, dim_DF, gamma = build_sample_DF(Q, J)
    if D_F is None:
        print("  [error] D_F construction failed")
        return None
    print(f"  [build] D_F dim={dim_DF}, ({time.time()-t0:.1f}s)")

    # Natural scale α = ‖L‖_F / ‖D_F‖_F (from g6a_multiscale_spectral_v1)
    tr_L2  = float(np.trace(L @ L).real)
    tr_DF2 = float(np.trace(D_F @ D_F).real)
    alpha = float(np.sqrt(tr_L2 / tr_DF2)) if tr_DF2 > 1e-15 else 1.0
    D_F_s = D_F * alpha

    D = L + D_F_s

    # Compute spectrum
    print(f"  [spec] computing spec(D)...")
    t0 = time.time()
    eig_D = np.linalg.eigvalsh(D)
    eig_D = np.sort(eig_D)
    eig_D2 = eig_D ** 2
    eig_D2_sorted = np.sort(eig_D2)
    print(f"  [spec] done ({time.time()-t0:.1f}s)")

    # K_ω spectrum (β=1, Λ=1 normalisation; scale-invariant ratios)
    # K_ω = D² (up to overall β/Λ² scale + additive log Z)
    # We report spec(D²) directly as proxy for K_ω spectrum.

    spec = {
        'name': name, 'n': n, 'dim_DF': dim_DF, 'alpha': alpha,
        'eig_D':  eig_D,
        'eig_D2': eig_D2_sorted,
    }

    # Reporting
    print(f"\n  [report] D = L + α·D_F at natural scale α={alpha:.4f}")
    print(f"          n={n}, dim H = {n} (Hilbert space C^n)")
    print(f"          spec(D)  range: [{eig_D[0]:+.4f}, {eig_D[-1]:+.4f}]")
    print(f"          spec(D²) range: [{eig_D2_sorted[0]:.6f}, {eig_D2_sorted[-1]:.4f}]")

    # Ground state + gap
    e0 = eig_D2_sorted[0]
    near_zero = np.sum(eig_D2_sorted < 1e-6)
    print(f"          ground state eigenvalue (D²): {e0:.6e}")
    print(f"          near-zero modes (D² < 1e-6): {near_zero}")

    # Gap structure
    if len(eig_D2_sorted) > 1:
        gaps = np.diff(eig_D2_sorted)
        first_real_gap_idx = next((i for i, g in enumerate(gaps) if g > 1e-6), -1)
        if first_real_gap_idx >= 0:
            spec_gap = gaps[first_real_gap_idx]
            print(f"          first gap at index {first_real_gap_idx}: "
                  f"Δ = {spec_gap:.4e}")
        max_gap_idx = int(np.argmax(gaps))
        print(f"          largest gap: index {max_gap_idx}, "
              f"Δ_max = {gaps[max_gap_idx]:.4e}")

    # Distinct eigenvalues (degeneracy)
    rounded = np.round(eig_D2_sorted, decimals=8)
    unique = np.unique(rounded)
    print(f"          distinct eigenvalues (D², rounded 8dp): {len(unique)}")
    print(f"          mean degeneracy: {n / len(unique):.2f}")

    # Spectrum statistics
    print(f"\n  [report] spec(D²) statistics:")
    print(f"          mean:    {eig_D2_sorted.mean():.4f}")
    print(f"          std:     {eig_D2_sorted.std():.4f}")
    print(f"          median:  {np.median(eig_D2_sorted):.4f}")
    print(f"          quartiles (25/75): "
          f"{np.percentile(eig_D2_sorted, 25):.4f} / "
          f"{np.percentile(eig_D2_sorted, 75):.4f}")

    # Top 12 + bottom 12 (the morphogenesis-time mode endpoints)
    print(f"\n  [report] bottom 12 eigenvalues of D² (low-frequency morphogenesis):")
    for i, ev in enumerate(eig_D2_sorted[:12]):
        print(f"          λ_{i:>3d} = {ev:.6e}")
    print(f"  [report] top 12 eigenvalues of D² (high-frequency morphogenesis):")
    for i, ev in enumerate(eig_D2_sorted[-12:]):
        print(f"          λ_{n-12+i:>3d} = {ev:.4e}")

    return spec


def main():
    seed = 42
    rng = np.random.default_rng(seed)
    psi_init = {v: haar_C3(rng) for v in range(6)}

    print("=" * 78)
    print("  Modular Hamiltonian Spectrum K_ω on Q102 (and family baselines)")
    print("  Per S181 — observation-only morphogenesis-time spectrum")
    print("=" * 78)

    results = []
    # Q48 baseline
    res48 = compute_modular_spectrum("Q48 = C(M(G₀))    [baseline]", G0_cyclic,
                                     psi_init, depth=5)
    if res48: results.append(res48)

    rng = np.random.default_rng(seed)
    psi_init = {v: haar_C3(rng) for v in range(6)}
    # Q84 baseline
    res84 = compute_modular_spectrum("Q84 = C(M(Adjacent))    [baseline]",
                                     adjacent_ternary, psi_init, depth=4)
    if res84: results.append(res84)

    rng = np.random.default_rng(seed)
    psi_init = {v: haar_C3(rng) for v in range(6)}
    # Q98 / Q102 (K₆³)
    res98 = compute_modular_spectrum("Q98 / Q102 = C(M(K₆³))    [HEADLINE — Q102 family]",
                                     lambda: complete_edges(), psi_init, depth=4)
    if res98: results.append(res98)

    print(f"\n{'='*78}")
    print(f"  SUMMARY — K_ω SPECTRUM ACROSS THE C-CLOSED FAMILY")
    print(f"{'='*78}")
    print(f"  {'Quotient':<24} {'n':>4} {'D_F':>5} {'α':>8} "
          f"{'min(D²)':>11} {'max(D²)':>11} {'mean(D²)':>11} "
          f"{'#distinct':>9}")
    print(f"  {'─'*92}")
    for r in results:
        rounded = np.round(r['eig_D2'], decimals=8)
        n_distinct = len(np.unique(rounded))
        print(f"  {r['name'][:24]:<24} {r['n']:>4} {r['dim_DF']:>5} "
              f"{r['alpha']:>8.3f} "
              f"{r['eig_D2'][0]:>11.4e} {r['eig_D2'][-1]:>11.4e} "
              f"{r['eig_D2'].mean():>11.4f} {n_distinct:>9d}")

    print(f"\n{'='*78}")
    print(f"  INTERPRETATION")
    print(f"{'='*78}")
    print(f"""
  The K_ω spectrum at the spectral-action thermal vacuum is
    K_ω eigenvalues = (β/Λ²) · spec(D²) + log(Z) · 1
  so spec(D²) reported above IS the morphogenesis frequency
  spectrum on Q102 (and family members), modulo overall scale β/Λ²
  and an additive constant from the partition function.

  Q102's morphogenesis frequency content is what dictates the
  characteristic time-scales of the unfolding from zygote to
  observed structure (S180).  Each eigenvalue is an analytic
  observable — no instantiation, no time-stepping.

  The number of distinct eigenvalues (degeneracy structure) is the
  natural measure of how many independent morphogenesis frequency
  modes exist.  High degeneracy means the modular flow has many
  identical-frequency directions; low degeneracy means rich
  spectral structure.

  Critical scope: this script computes the SPECTRUM (eigenvalues
  of K_ω = β·D²/Λ² + const) — a structural / linear-algebraic
  property of Q102.  It does NOT instantiate σ_t = e^{{-itK_ω}}
  by computing time-evolution; that would be out of S180 scope.
""")


if __name__ == '__main__':
    main()
